/*
 * This source file was generated by the Gradle 'init' task
 */
package org.home.work;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import io.micronaut.runtime.Micronaut;

public class App {
    public static ObjectMapper objectMapper = new ObjectMapper().registerModule(new JavaTimeModule());

    public static void main(String[] args) {
        Micronaut.run(App.class, args);
    }
}
